filebeat.inputs:
  - type: log
    paths:
      - /usr/share/logs/*.json
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "bookportal-logs-%{+YYYY.MM.dd}"

setup.template:
  name: "bookportal-logs"
  pattern: "bookportal-logs-*"