# Docker production Spring profile
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=update
frontend.url=${FRONTEND_URL:http://frontend}